homeout=loadlayout({
  LinearLayout;
  backgroundColor="0xffffffff";
  layout_height="fill";
  orientation="vertical";
  layout_width="fill";
  {
    LinearLayout;
    layout_height="61dp";
    orientation="horizontal";
    layout_gravity="top|center";
    gravity="top|center";
    layout_width="fill";
    FocusableInTouchMode=true;
    Focusable=true;

    {
      ImageView;
      layout_marginLeft="10dp";
      layout_height="20dp";
      id="goback";
      colorFilter="#757575";
      layout_gravity="center|right";
      src="static/img/search/left.png";
      layout_marginRight="5dp";
      layout_width="21dp";
    };
    {
      EditText;
      background="0xffeeeeee";
      layout_weight="1";
      textSize="13dp";
      hint="输入关键词或播放地址";
      layout_marginTop="1dp";
      lines="1";
      id="searchtext";
      layout_gravity="left|center";
      layout_marginRight="5dp";
      singleLine="true";
      imeOptions="actionSearch";
      Typeface=Typeface.createFromFile(File(activity.getLuaDir().."/static/font/font.ttf"));
    };
    {
      ImageView;
      layout_marginRight="15dp";
      layout_height="25dp";
      id="searchdelete";
      colorFilter="#757575";
      layout_gravity="center|right";
      src="static/img/search/delete.png";
      visibility=8;
      layout_width="21dp";
    };
    {
      LinearLayout;
      layout_gravity="center";
      layout_height="15dp";
      backgroundColor="0xFF000000";
      layout_width="1";
    };

    {
      ImageView;
      src="static/img/search/search.png";
      layout_width="21dp";
      layout_height="21dp";
      colorFilter="#757575";
      layout_gravity="center";
      layout_marginLeft="15dp";
      layout_marginRight="15dp";
      id="searchevent";
    };
    {
      TextView;

      layout_width="wrap";
      layout_height="wrap";
      Visibility=8;
      layout_gravity="center";
      layout_marginLeft="15dp";
      layout_marginRight="15dp";
      id="searcheventtext";
      text="前往",
      gravity="center";
      Typeface=Typeface.createFromFile(File(activity.getLuaDir().."/static/font/font.ttf"));

      textSize="13dp"
    };


  };
  {
    TextView,--文本框控件
    layout_width='fill',
    layout_height='1dp',
    backgroundColor=0x11000000,
  },


  {
    LinearLayout;
    layout_height="wrap_content";
    orientation="vertical";
    layout_width="match_parent";
    id="searchtip";
    visibility=4;
    {
      LinearLayout;
      layout_height="wrap_content";
      orientation="horizontal";
      layout_width="match_parent";
      {
        TextView;

        layout_weight="1";
        layout_margin="10dp";
        textSize="17dp";
        text="热门搜索";
        textColor="#227CEA";
        -- Typeface=Typeface.createFromFile(File(activity.getLuaDir().."/static/font.ttf"));
      };

    };
    {
      ScrollView;
      VerticalScrollBarEnabled=false;
      layout_width="match_parent";
      {
        LinearLayout;
        id="searchtipout";
        layout_height="40%h";
        orientation="vertical";
        layout_width="match_parent";
      };
    };

  };
  {
    LinearLayout;
    layout_height="fill";
    orientation="vertical";
    layout_width="fill";
    id="bodyout";

    {
      LinearLayout;
      layout_marginBottom="30dp";
      layout_height="35%h";
      orientation="vertical";
      id="hotout";
      layout_width="match_parent";
      {
        TextView;
        textColor="#227CEA";
        text="热门推荐";
        layout_margin="10dp";
        textSize="17dp";
      };
      {
        ScrollView;
        layout_weight="1";
        VerticalScrollBarEnabled=false;
        layout_width="match_parent";
        {
          LinearLayout;
          id="hotdataout";
          layout_height="fill";
          orientation="vertical";
          layout_width="match_parent";
        };
      };
    };

    {
      LinearLayout;
      layout_height="wrap_content";
      orientation="vertical";
      layout_width="match_parent";
      id="searchhistoryout";
      visibility=4;
      {
        LinearLayout;
        layout_height="wrap_content";
        orientation="horizontal";
        layout_width="match_parent";
        {
          TextView;
          layout_weight="1";
          layout_margin="10dp";
          textSize="17dp";
          text="搜索历史";
          textColor="#227CEA";
        };
        {
          ImageView;
          layout_height="20dp";
          id="resertsearchhistory";
          colorFilter="#757575";
          layout_gravity="center|right";
          src="static/img/search/delete.png";
          layout_margin="10dp";
          layout_width="21dp";
        };
      };
      {
        ScrollView;
        VerticalScrollBarEnabled=false;
        layout_width="match_parent";
        {
          LinearLayout;
          id="searchhistoryitemout";
          layout_height="fill";
          orientation="vertical";
          layout_width="match_parent";
        };
      };
    };

  };
})


